# Marco
version: "3"
services:
  base:
    build:
      context: .
      dockerfile: dockerfiles/base.Dockerfile
    image: "iamos/terraria-base:latest"
  vanilla:
    build:
      context: .
      dockerfile: dockerfiles/vanila.Dockerfile
    image: "iamos/terraria-vanilla:latest"
  tmodloader:
    build:
      context: .
      dockerfile: dockerfiles/tModloader.Dockerfile
    image: "iamos/terraria-tmodloader:latest"
